name: Terratest
on:
  schedule:
    - cron: "0 10 * * 6"
  pull_request:
    branches:
      - master
  push:
    paths-ignore:
      - '**/README.md'  

env:
  TERRAFORM_VERSION: 1.8.0
  GO_VERSION: 1.22
  AWS_REGION: "us-west-2" 

# Set to the repository name
concurrency: terraform-module-template

jobs:
  build:
    name: Test XXXXX Module
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Setup Terraform  
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ env.AWS_REGION }}

      # - name: Run the Tests
      #   run: cd ./test; go test -v
